


//#include"../network/jmesh_netkey.h"
//#include"../foundation/state/jmesh_appkey.h"
//#include"../foundation/state/jmesh_TTL.h"
//#include"jmesh_device.h"
//#include"../access/jmesh_access.h"

#include"jmesh_config.h"
#ifdef JMESH_SAVE_DEFINE
JMESH_SAVE_CREATE(JMESH_SAVE_FEATURES)
JMESH_SAVE_CREATE(JMESH_SAVE_ADDR)
JMESH_SAVE_CREATE(JMESH_SAVE_DEFAULT_TTL)
JMESH_SAVE_CREATE(JMESH_SAVE_IV_INDEX)
JMESH_SAVE_CREATE(JMESH_SAVE_SEQ)
JMESH_SAVE_CREATE(JMESH_SAVE_STATE_FLAGS)
JMESH_SAVE_CREATE(JMESH_SAVE_BAUTRATE)
JMESH_SAVE_CREATE(JMESH_SAVE_REALCOMM_PARA)
JMESH_SAVE_BUFFER_CREATE(JMESH_SAVE_NETKEY, JMESH_NETKEY_MAX_NUM)
JMESH_SAVE_BUFFER_CREATE(JMESH_SAVE_APPKEY, JMESH_APPKEY_MAX_NUM)
JMESH_SAVE_BUFFER_CREATE(JMESH_SAVE_DEVICE,JMESH_DEVICE_MAX_NUM)
JMESH_SAVE_BUFFER_CREATE(JMESH_SAVE_MODEL,JMESH_MODEL_MAX_NUM)

#endif // JMESH_SAVE_H

